### ISSUE TITLE
Tests: Add tests and improve coverage

### ISSUE THREAD

**Issue by anirudhsudhir** [acmpesuecc/anna#59]
- Write tests for various components of the ssg
  - [x] tests for `helper` package
  - [x] tests for `engine` package
  - [x] tests for `parser` package
  - [x] tests for the `zettel` feature 
  - [x] benchmark for `main.go`
  
- [x] Add status checks for PRs and fix netlify deploy preview

- [x] Minimum test coverage of 50% for all packages
  - [x] Improve engine/ test coverage

**Comment by bwaklog** [comment]
- Reached 71.2% coverage with engine package : [perf:154405e](github.com/acmpesuecc/anna/tree/154405e69ac99184cff6d8e95ed42afa5b13af1c)
- Added tests for `engine` pacakge

**Comment by anirudhsudhir** [comment]
- [x] Remove generated test output files and ignore the directories in .gitignore
- [x] Add a cleanup script to delete test output

**Comment by anirudhsudhir** [comment]
- [x] Add tests got helper/ and notes/
- [x] coverage of >50% for all packages under pkg/
