### ISSUE TITLE
JSON Generator

### ISSUE THREAD

**Issue by anirudhsudhir** [acmpesuecc/anna#62]
- [x] Write a generator to produce a merged JSON output of post URLs, titles and their description.

**Comment by bwaklog** [comment]
added a `ParseJsonMerged` method to `parser.go` in [adhesh's branch](https://github.com/acmpesuecc/anna/tree/ad7a86b85ec5e567b0952a5809f6abf32b26a8d1). It creates a json file with merged data at `static/scripts/merged.json` with the following content: 

```json
{
    "docs.md": {
        "CompleteURL": "docs.html",
        "FilenameWithoutExtension": "docs",
        "Frontmatter": {
            "Title": "Anna Documentation",
            "Date": "",
            "Draft": false,
            "JSFiles": null,
            "Type": "",
            "Description": "",
            "PreviewImage": "",
            "Tags": null
        },
        "Tags": null
    }
```

**Comment by bwaklog** [comment]
@anirudhsudhir review `anna_engine_test.go` and engine tests file structure for the unit tests related to this function.

There should be no merge conflicts in my opinion. Keep this issue open, as of now its just a pure js implementation, and needs to be fully integrated with Adhesh's wasm version

**Comment by bwaklog** [comment]
@anirudhsudhir theres a small issue with the json generation. We copy static directory contents before we create the the `index.json` file. This becomes an issue while working with personal sites. There is a creation of index.json but it isn't part of the rendered directory

<img width="631" alt="image" src="https://github.com/acmpesuecc/anna/assets/91192289/35773457-d5ef-4585-ad53-19c2868de9b9">

snippet from `anna.go`

```go
helper.CopyDirectoryContents(helpers.SiteDataPath+"static/", helpers.SiteDataPath+"rendered/static/")
e.GenerateJSONIndex(helpers.SiteDataPath
```
