### ISSUE TITLE
chore/ci: tag v1.0.0-alpha release and deploy matrix builds

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/anna#76]
Tag a `v1.0.0-alpha` release by wednesday, for the fireside talk. Ideally sign using our own GPG keys.
Use go-releaser and gh-actions to deploy matrix builds for 3 target platforms: 
- [x] `darwin` (setup notarized builds)
- [x]  `Windows`
- [x] `GNU/linux`

Should cover 3/4 of #65

**Comment by bwaklog** [comment]
@polarhive we've got a few builds for dawin and linux (arm64) available for testing in the following repo : [test-binary](https://github.com/anirudhsudhir/testing-binary/releases/tag/v0.1.1)
